// Mocks generated by Mockito 5.4.2 from annotations
// in marvel_app/test/lib/data/repositories/api_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dio/dio.dart' as _i2;
import 'package:marvel_app/data/datasources/remote/marvel_api_service_impl.dart'
    as _i3;
import 'package:marvel_app/domain/models/requests/marvel_characters_request.dart'
    as _i6;
import 'package:marvel_app/domain/models/responses/marvel_characters_response.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDio_0 extends _i1.SmartFake implements _i2.Dio {
  _FakeDio_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponse_1<T> extends _i1.SmartFake implements _i2.Response<T> {
  _FakeResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MarvelApiServiceImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockMarvelApiServiceImpl extends _i1.Mock
    implements _i3.MarvelApiServiceImpl {
  @override
  _i2.Dio get dio => (super.noSuchMethod(
        Invocation.getter(#dio),
        returnValue: _FakeDio_0(
          this,
          Invocation.getter(#dio),
        ),
        returnValueForMissingStub: _FakeDio_0(
          this,
          Invocation.getter(#dio),
        ),
      ) as _i2.Dio);
  @override
  _i4.Future<_i2.Response<_i5.MarvelCharactersResponse>> getMarvelCharacters(
          _i6.MarvelCharactersRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMarvelCharacters,
          [request],
        ),
        returnValue:
            _i4.Future<_i2.Response<_i5.MarvelCharactersResponse>>.value(
                _FakeResponse_1<_i5.MarvelCharactersResponse>(
          this,
          Invocation.method(
            #getMarvelCharacters,
            [request],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Response<_i5.MarvelCharactersResponse>>.value(
                _FakeResponse_1<_i5.MarvelCharactersResponse>(
          this,
          Invocation.method(
            #getMarvelCharacters,
            [request],
          ),
        )),
      ) as _i4.Future<_i2.Response<_i5.MarvelCharactersResponse>>);
}
